schema {
    query: Query
}

enum MediaType {
    ANIME
    MANGA
}

type Media {
    id: Int!
    idMal: Int
    title: MediaTitle
    airingSchedule: AiringScheduleConnection
    duration: Int
    type: MediaType
    coverImage: CoverImage
    bannerImage: String
}

type MediaTitle {
    english: String
    native: String
    romaji: String
}

type AiringScheduleConnection {
    nodes: [AiringSchedule]
}

type AiringSchedule {
    id: Int!
    airingAt: Int!
    episode: Int!
}

type CoverImage {
    extraLarge: String
    large: String
    medium: String
    color: String
}

type Page {
    media(id_in: [Int!]!): [Media!]
}

type Query {
    "Find media by IDs"
    Page: Page!
}
