[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7"
actix-governor = "0.7"
actix-web = "4.11"
actix-web-lab = "0.24"
anilist = { path = "../anilist" }
argon2 = { version = "0.5", features = [ "std" ] }
async-stripe = "=1.0.0-rc.5"
async-stripe-billing = { version = "=1.0.0-rc.5", features = ["subscription", "subscription_item", "billing_portal_session", "serialize", "deserialize"] }
async-stripe-checkout = { version = "=1.0.0-rc.5", features = ["checkout_session", "serialize", "deserialize"] }
async-stripe-core = { version = "=1.0.0-rc.5", features = ["customer", "serialize", "deserialize"] }
async-stripe-shared = { version = "=1.0.0-rc.5", features = ["serialize", "deserialize"] }
async-stripe-types = { version = "=1.0.0-rc.5", features = ["serialize", "deserialize"] }
async-stripe-webhook = { version = "=1.0.0-rc.5", features = ["deserialize", "async-stripe-checkout", "async-stripe-billing", "async-stripe-core"] }
chrono = { version = "0.4", features = [ "serde" ] }
common = { path = "../common", features = ["utoipa"] }
config = "0.15"
email_address = "0.2"
env_logger = "0.11"
futures = "0.3"
futures-util = "0.3"
google-oauth = { version = "1.11" }
icalendar = "0.17.3"
jsonwebtoken = { version = "10.2", features = [ "aws_lc_rs" ] }
lettre = { version = "0.11", features = ["tokio1-native-tls", "smtp-transport", "builder"] }
log = "0.4"
metrics = "0.24.3"
metrics-exporter-prometheus = "0.18.1"
rand = "0.9"
redis = { version = "1.0", features = [ "aio", "tokio-comp" ] }
secrecy = { version = "0.10", features = [ "serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres", "macros", "chrono", "migrate" ] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
utoipa = { version = "5", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }

[dev-dependencies]
metrics-util = "0.20.1"
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
