query GetItems($ids: [Int!]!) {
    Page {
        media(id_in: $ids) {
            id
            idMal
            title {
                romaji
                english
                native
            }
            duration
            airingSchedule(notYetAired: true) {
                nodes {
                    id
                    airingAt
                    episode
                }
            }
            mediaType: type
            coverImage {
                extraLarge
                large
                medium
                color
            }
            bannerImage
            recommendations(sort: RATING_DESC, page: 1, perPage: 5) {
                edges {
                    node {
                        rating
                        mediaRecommendation {
                            id
                            idMal
                            title {
                                romaji
                                english
                                native
                            }
                            coverImage {
                                extraLarge
                                large
                                medium
                                color
                            }
                        }
                    }
                }
            }
        }
    }
}
